### ISSUE TITLE
is it still working?

### ISSUE THREAD

**Issue by NoNValid** [seemoo-lab/opendrop#4]
Hi, I'm trying to run the opendrop on the my Ubuntu machine 18.04.

I'm using the last owl and opendrop, and airmon-ng to switch the WiFi interface to monitor mode,
for the wifi cards I tried my build-in card from intel and external alfa wifi catds with realtek driver.

I followed this blog https://owlink.org/2019/05/16/howto-use-airdrop-on-raspberry-pi-3.html
and everything install and worked fine.

but "opendrop find" dose not find any devices running airdrop (iPhone IOS 12.3.1)
on the owl shell I can watch some mac address when the phone try to look for airdrop destination but without names.

I tried to change channels on owl but it did not work.
even tried to set the "opendrop receive" and I can not find it from the iphone airdrop.

I'm trying to run it now on RPI Zero but I do not think it will make a difference.

**Comment by schmittner** [comment]
You can try to use a 5GHz channel (44 or 149 depending on your regdom) which generally performs a lot better by staring owl via `-c 44`. Note that if your wireless card supports Netlink then owl will take care of putting your card in monitor mode for you (do not use `-N`!)

Unfortunately, I don't have time to test and provide support for other configurations (i.e., RPi or AR9280).

**Comment by Lonkus** [comment]
I'm limited to working over 2G due to my wireless adapter, so I cannot test OpenDrop over 5G. I followed the same guide at https://owlink.org/2019/05/16/howto-use-airdrop-on-raspberry-pi-3.html and installed everything successfully. I also can't find any receivers using `opendrop find`, and I couldn't find my RPi under AirDrop using `opendrop receive`. 

I am using a Realtek 5370 chipset with my Raspberry Pi 2 B. I am using Raspbian Buster (kernel 4.19).

**Comment by schmittner** [comment]
Again, I do not (and cannot) provide support for configurations other than the ones that I have tested myself. I'm closing this.
